#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

  cookbook 'nginx', :git => 'git://github.com/opscode-cookbooks/nginx.git'
  cookbook 'redis2', git: "git://github.com/Fewbytes/redis2-cookbook.git"
# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
  # :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
